pub mod fire_player_exotic;
pub mod player_exotic_ammunition_consumption;
pub mod player_exotic_collision;
pub mod player_exotic_lifetime;
pub mod player_exotic_movement;
pub mod spawn_player_exotic_collision_sound;
pub mod spawn_player_exotic_sound;
pub mod spawn_player_exotic_sprite;
pub mod spawn_player_exotic_sprite_on_load;
