pub mod fire_player_blaster;
pub mod player_blaster_ammunition_consumption;
pub mod player_blaster_collision;
pub mod player_blaster_lifetime;
pub mod player_blaster_movement;
pub mod spawn_player_blaster_collision_sound;
pub mod spawn_player_blaster_sound;
pub mod spawn_player_blaster_sprite;
pub mod spawn_player_blaster_sprite_on_load;
