pub mod fire_player_mine;
pub mod player_mine_ammunition_consumption;
pub mod player_mine_collision;
pub mod player_mine_lifetime;
pub mod player_mine_movement;
pub mod spawn_player_mine_collision_sound;
pub mod spawn_player_mine_sound;
pub mod spawn_player_mine_sprite;
pub mod spawn_player_mine_sprite_on_load;
